"""FastStrap - Modern Bootstrap 5 components for FastHTML.

Build beautiful web UIs in pure Python with zero JavaScript knowledge.
"""

from importlib import metadata as _metadata

try:
    __version__ = _metadata.version("faststrap")
except _metadata.PackageNotFoundError:
    __version__ = "0.0.0+local"
__author__ = "FastStrap Contributors"
__license__ = "MIT"

# Core functionality

# Display
# Presets (HTMX interaction helpers)
from . import presets
from .accessibility import FocusTrap, LiveRegion, SkipLink, VisuallyHidden
from .components.display import (
    Avatar,
    AvatarGroup,
    Badge,
    BadgeGroup,
    BsTable,
    BsTBody,
    BsTCell,
    BsTHead,
    BsTRow,
    Card,
    Carousel,
    CarouselItem,
    Chart,
    CodeBlock,
    DataTable,
    EmptyState,
    Figure,
    FlipCard,
    GlowCard,
    Image,
    JsonViewer,
    KeyValueList,
    KPICard,
    MapView,
    Markdown,
    Mermaid,
    MetricCard,
    RecordDetail,
    ResultCard,
    RevealCard,
    Sheet,
    SSETarget,
    StatCard,
    StatusBadge,
    Stepper,
    StepperStep,
    Svg,
    Table,
    TBody,
    TCell,
    TextClamp,
    THead,
    TiltCard,
    Timeline,
    TimelineItem,
    TrendCard,
    TRow,
    datatable_export_params,
    datatable_page_url,
    datatable_query_params,
    render_svg,
)

# Feedback
from .components.feedback import (
    Alert,
    ConfirmAction,
    ConfirmDialog,
    DotsLoader,
    ErrorDialog,
    ErrorPage,
    ErrorToast,
    InfoToast,
    InstallPrompt,
    Modal,
    ModernToast,
    ModernToastStack,
    NoticeAlert,
    NoticeToast,
    NotificationCenter,
    Placeholder,
    PlaceholderButton,
    PlaceholderCard,
    PolygonLoader,
    Popover,
    Progress,
    ProgressBar,
    ProgressRing,
    PulseLoader,
    RingLoader,
    ShadowLoader,
    SimpleToast,
    Spinner,
    SuccessToast,
    Toast,
    ToastContainer,
    Tooltip,
    TypewriterLoader,
    WarningToast,
    WaveLoader,
)

# Forms
from .components.forms import (
    Button,
    ButtonGroup,
    ButtonToolbar,
    CalendarDatePicker,
    Checkbox,
    CloseButton,
    DateRangePicker,
    ExportButton,
    FileInput,
    FilterBar,
    FloatingActionButton,
    FloatingLabel,
    Form,
    FormBuilder,
    FormErrorSummary,
    FormGroup,
    FormGroupFromErrors,
    FormSection,
    FormWizard,
    GradientButton,
    InlineEditor,
    Input,
    InputGroup,
    InputGroupText,
    LiveValidationField,
    MultiSelect,
    Radio,
    Range,
    RangeSlider,
    SearchableSelect,
    Select,
    Switch,
    ThemeToggle,
    ToggleGroup,
    ValidationMessage,
    WizardStep,
    extract_field_error,
    map_formgroup_validation,
)

# Layout
from .components.layout import (
    Center,
    Cluster,
    Col,
    Container,
    DashboardGrid,
    Hero,
    PageHeader,
    ParallaxSection,
    Row,
    Stack,
)

# Navigation
from .components.navigation import (
    Accordion,
    AccordionItem,
    BottomNav,
    BottomNavItem,
    Breadcrumb,
    Collapse,
    CommandItem,
    CommandPalette,
    Drawer,
    Dropdown,
    DropdownDivider,
    DropdownItem,
    GlassNavbar,
    GlassNavItem,
    ListGroup,
    ListGroupItem,
    Navbar,
    Pagination,
    Scrollspy,
    SidebarNavbar,
    SidebarNavItem,
    TabPane,
    Tabs,
)

# Patterns
from .components.patterns import (
    Feature,
    FeatureGrid,
    FooterModern,
    NavbarModern,
    PricingGroup,
    PricingTier,
    Testimonial,
    TestimonialSection,
)
from .core._stability import beta, experimental, stable
from .core.assets import add_bootstrap, get_assets, mount_assets
from .core.base import merge_classes
from .core.effects import Fx
from .core.registry import (
    find_components,
    get_component,
    get_components_by_pattern,
    list_component_metadata,
    list_components,
    register,
)
from .core.theme import (
    UNSET,
    Theme,
    create_theme,
    get_builtin_theme,
    list_builtin_themes,
    reset_component_defaults,
    resolve_defaults,
    set_component_defaults,
    theme_variant_css,
)
from .integrations import (
    CHARTJS_CDN_URL,
    CHARTJS_VERSION,
    GSAP_CDN_URL,
    GSAP_VERSION,
    ChartJS,
    ChartJSType,
    Gsap,
    GsapPreset,
    GsapReveal,
    Motion,
    MotionPreset,
    add_chartjs,
    add_gsap,
    chartjs_assets,
    gsap_assets,
)
from .layouts import AuthLayout, DashboardLayout, LandingLayout

# PWA
from .pwa import PwaMeta, add_pwa

# SEO helpers
from .seo import SEO, PageMeta, StructuredData

# Utils
from .utils import cleanup_static_resources, get_faststrap_static_url
from .utils.attrs import convert_attrs
from .utils.icons import Icon

__all__ = [
    # Core
    "add_bootstrap",
    "get_assets",
    "mount_assets",
    "merge_classes",
    "convert_attrs",
    "find_components",
    "get_component",
    "get_components_by_pattern",
    "list_component_metadata",
    "list_components",
    "register",
    "theme_variant_css",
    "add_chartjs",
    "add_gsap",
    "chartjs_assets",
    "gsap_assets",
    "CHARTJS_CDN_URL",
    "CHARTJS_VERSION",
    "GSAP_CDN_URL",
    "GSAP_VERSION",
    "ChartJS",
    "ChartJSType",
    "Gsap",
    "GsapPreset",
    "GsapReveal",
    "Motion",
    "MotionPreset",
    # Accessibility
    "SkipLink",
    "LiveRegion",
    "VisuallyHidden",
    "FocusTrap",
    # PWA
    "PwaMeta",
    "add_pwa",
    # Theme
    "Theme",
    "UNSET",
    "create_theme",
    "get_builtin_theme",
    "list_builtin_themes",
    "set_component_defaults",
    "reset_component_defaults",
    "resolve_defaults",
    # Forms
    "Button",
    "CloseButton",
    "ButtonGroup",
    "ButtonToolbar",
    "Checkbox",
    "FileInput",
    "Form",
    "FormBuilder",
    "FormSection",
    "FormWizard",
    "FormGroup",
    "FormErrorSummary",
    "CalendarDatePicker",
    "DateRangePicker",
    "ExportButton",
    "FilterBar",
    "FloatingActionButton",
    "GradientButton",
    "Radio",
    "Switch",
    "Range",
    "MultiSelect",
    "RangeSlider",
    "Input",
    "InputGroup",
    "InputGroupText",
    "InlineEditor",
    "FloatingLabel",
    "SearchableSelect",
    "Select",
    "ThemeToggle",
    "ToggleGroup",
    "LiveValidationField",
    "ValidationMessage",
    "WizardStep",
    "extract_field_error",
    "map_formgroup_validation",
    "FormGroupFromErrors",
    # Display
    "Badge",
    "BadgeGroup",
    "Avatar",
    "AvatarGroup",
    "Card",
    "Carousel",
    "CarouselItem",
    "Chart",
    "CodeBlock",
    "DataTable",
    "datatable_export_params",
    "datatable_page_url",
    "datatable_query_params",
    "EmptyState",
    "Figure",
    "FlipCard",
    "GlowCard",
    "Image",
    "JsonViewer",
    "KPICard",
    "KeyValueList",
    "MapView",
    "Markdown",
    "Mermaid",
    "RecordDetail",
    "ResultCard",
    "RevealCard",
    "Sheet",
    "MetricCard",
    "Svg",
    "StatCard",
    "SSETarget",
    "Stepper",
    "StepperStep",
    "StatusBadge",
    "TextClamp",
    "Timeline",
    "TimelineItem",
    "TiltCard",
    "BsTable",
    "BsTHead",
    "BsTBody",
    "BsTRow",
    "BsTCell",
    "Table",
    "THead",
    "TBody",
    "TRow",
    "TCell",
    "TrendCard",
    "render_svg",
    "Alert",
    "DotsLoader",
    "ErrorPage",
    "ErrorDialog",
    "InstallPrompt",
    "ConfirmAction",
    "ConfirmDialog",
    "Toast",
    "SimpleToast",
    "NoticeToast",
    "NoticeAlert",
    "SuccessToast",
    "ErrorToast",
    "WarningToast",
    "InfoToast",
    "ToastContainer",
    "Modal",
    "ModernToast",
    "ModernToastStack",
    "NotificationCenter",
    "Placeholder",
    "PlaceholderButton",
    "PlaceholderCard",
    "PolygonLoader",
    "Popover",
    "Tooltip",
    "Progress",
    "ProgressBar",
    "ProgressRing",
    "PulseLoader",
    "RingLoader",
    "ShadowLoader",
    "Spinner",
    "TypewriterLoader",
    "WaveLoader",
    # Layout
    "Container",
    "Row",
    "Col",
    "Center",
    "Cluster",
    "DashboardGrid",
    "Hero",
    "PageHeader",
    "ParallaxSection",
    "Stack",
    # Navigation
    "Accordion",
    "AccordionItem",
    "Collapse",
    "CommandItem",
    "CommandPalette",
    "Drawer",
    "ListGroup",
    "ListGroupItem",
    "Navbar",
    "BottomNav",
    "BottomNavItem",
    "GlassNavbar",
    "GlassNavItem",
    "Scrollspy",
    "SidebarNavbar",
    "SidebarNavItem",
    "Pagination",
    "Breadcrumb",
    "Dropdown",
    "DropdownItem",
    "DropdownDivider",
    "Tabs",
    "TabPane",
    # Layouts
    "AuthLayout",
    "DashboardLayout",
    "LandingLayout",
    # Patterns
    "NavbarModern",
    "Feature",
    "FeatureGrid",
    "FooterModern",
    "Testimonial",
    "TestimonialSection",
    "PricingGroup",
    "PricingTier",
    # Presets
    "presets",
    # SEO
    "SEO",
    "PageMeta",
    "StructuredData",
    # Utils
    "Icon",
    "get_faststrap_static_url",
    "cleanup_static_resources",
    # Metadata
    "__version__",
    "__author__",
    "__license__",
    "Fx",
    # Stability
    "stable",
    "beta",
    "experimental",
]
